tracker: update 3.7.1 -> 3.8.0
- Dont inherit python3native. It seems to be unneeded
- Rename to tinysparql
- Drop dependencies for python3-pygobject-native and libarchive
- Disable tests by default
- Add PACKAGECONFIG for avahi
- Fix sed hack to keep buildpath out of enum-types.c
- Add patch that avoids to create compatibility links which would lead to package_qa error:
Path /home/flk/poky/build-hypr/tmp/work/corei7-64-poky-linux/tinysparql/3.8.0/sstate-build-package/package/usr/lib/libtracker-sparql-3.0.so is owned by uid 1000, gid 100, which doesn't match any user/group on target. This may be due to host contamination.
- Refresh fix-reproducibility.patch and additionally edit tracker-http.c to avoid another buildpath leakage

Exception: Exception: KeyError: 'getpwuid(): uid not found: 1000'
Signed-off-by: Khem Raj <raj.khem@gmail.com>